In [1]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV

import warnings

In [2]:
df= pd.read_csv('data\Titanic-Dataset.csv')

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\NishantHP\AppData\Local\Temp\ipykernel_35684\1710031744.py:1: SyntaxWarning: invalid escape sequence '\T'
  df= pd.read_csv('data\Titanic-Dataset.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
df.drop('Cabin',axis= 1,inplace=True)

In [6]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\NishantHP\AppData\Local\Temp\ipykernel_35684\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [7]:
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

C:\Users\NishantHP\AppData\Local\Temp\ipykernel_35684\3717664479.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

In [8]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [9]:
X=df.drop(columns=['Survived'],axis=1)

In [10]:
Y=df['Survived']

In [11]:
X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [12]:
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [13]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer


num_features=X.select_dtypes(exclude='object').columns
cat_features=X.select_dtypes(include='object').columns

num_transformer=StandardScaler()
ct_transfomer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ('oneHotencoder',ct_transfomer,cat_features),
        ("standardScaler",num_transformer,num_features)])

In [14]:
X=preprocessor.fit_transform(X)

In [15]:
X.shape

(891, 1583)

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((712, 1583), (179, 1583))

In [17]:
def eval_model(true, predicted):
    mae=mean_absolute_error(true, predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mse)
    r2_square= r2_score(true,predicted)
    return mae, rmse, r2_square

In [18]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]


for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, Y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = eval_model(Y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 =eval_model(Y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.3466
- Mean Absolute Error: 0.2728
- R2 Score: 0.5046
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 0.4845
- Mean Absolute Error: 0.4694
- R2 Score: 0.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4938
- Mean Absolute Error: 0.4786
- R2 Score: -0.0056
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 0.1299
- Mean Absolute Error: 0.1021
- R2 Score: 0.9281
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.3484
- Mean Absolute Error: 0.2739
- R2 Score: 0.4995
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 0.3228
- Mean Absolute Error: 0.2194
- R2 Score: 0.5560
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.3743
- Mean Absolute Error: 0.2380
- R2 Score: 0.4222
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.4358
- Mean Absolute Error: 0.1899
- R2 Score: 0.2167
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 0.1382
- Mean Absolute Error: 0.0708
- R2 Score: 0.9186
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.3817
- Mean Absolute Error: 0.1973
- R2 Score: 0.3992
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 0.3586
- Mean Absolute Error: 0.2976
- R2 Score: 0.4522
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.3856
- Mean Absolute Error: 0.3127
- R2 Score: 0.3869
===================================

In [21]:
pd.DataFrame(list(zip(model_list,r2_list)),columns=['Model_name','R2_score']).sort_values(by=['R2_score'],ascending=False)

                Model_name  R2_score
0        Linear Regression  0.504560
2                    Ridge  0.499452
3    K-Neighbors Regressor  0.422224
5  Random Forest Regressor  0.399210
6       AdaBoost Regressor  0.386927
4            Decision Tree  0.216731
1                    Lasso -0.005646